name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Run build script with secrets
        run: node index.js
        env:
          USER_PG: ${{secrets.USER_PG}}
          HOST_PG: ${{secrets.HOST_PG}}
          DATABASE_PG: ${{secrets.DATABASE_PG}}
          PORT_PG: ${{secrets.PORT_PG}} 
          PASSWORD_PG: ${{secrets.PASSWORD_PG}}




 
